#remote_theme: jekyll/minima # must force remote theme download because GitHub Pagss doesn't update their version
remote_theme: rahil627/minima-customized # i won't ever rememeber to update my forked version :(

# standard vars
title: "gorge's guardians: the natural way of life" #requires literal string due to the ':'
#description: a digital communal space that strives to follow the natural way of life

# theme sepecific stuff
minima:
  plugins:
   - jekyll-seo-tag

  skin: solarized-dark # a bit funky, but okay for now
  
#  author:
#    name: rahil627 aka rathewolf # does this go to seo?
#    email: '' # might cause an error without it

# custom theme vars
title-short: "gorge's guardians"
text-align: center
footer:
  left: 'a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a>'

# other vars
# convert newlines properly
kramdown:
  input: GFM
  hard_wrap: true
