title: nature's guardians: *the natural way* of life
#description: a digital community that strives to follow *the natural* way of life

remote_theme: jekyll/minima
minima:
  skin: solarized-dark # can try solarized-dark, but it's fugly
